// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtd89-_ePub-l1tlEwk4FGodr-087_uVs',
    appId: '1:146143801307:web:8b3ad57b8c1e5b77be01fe',
    messagingSenderId: '146143801307',
    projectId: 'flutter-project-2023',
    authDomain: 'flutter-project-2023.firebaseapp.com',
    storageBucket: 'flutter-project-2023.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfjwUPHmrFB0axGqQXJJWN3Tn1woHlh68',
    appId: '1:146143801307:android:c82075032fe185e1be01fe',
    messagingSenderId: '146143801307',
    projectId: 'flutter-project-2023',
    storageBucket: 'flutter-project-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQCcGp2Pfc7tI2Q-EC4r-1VRovngLeQyQ',
    appId: '1:146143801307:ios:8e836f68ef8c2175be01fe',
    messagingSenderId: '146143801307',
    projectId: 'flutter-project-2023',
    storageBucket: 'flutter-project-2023.appspot.com',
    iosClientId: '146143801307-p15f5b3njop242abbvvpr3h48432ctmq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject2023',
  );
}
